# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-12-29 07:16
from __future__ import unicode_literals

from django.db import migrations
import lfs.core.fields.thumbs


class Migration(migrations.Migration):
    dependencies = [
        ("lfs_carousel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carouselitem",
            name="image",
            field=lfs.core.fields.thumbs.ImageWithThumbsField(
                blank=True,
                null=True,
                sizes=((60, 60), (100, 100), (200, 200), (300, 300), (400, 400), (600, 600)),
                upload_to=b"images",
                verbose_name="Image",
            ),
        ),
    ]
