# Generated by Django 5.1.5 on 2025-02-10 04:54

import lfs.core.fields.thumbs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_carousel', '0002_auto_20201229_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=lfs.core.fields.thumbs.ImageWithThumbsField(blank=True, null=True, sizes=((60, 60), (100, 100), (200, 200), (300, 300), (400, 400), (600, 600)), upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='link',
            field=models.URLField(blank=True, default='', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Text'),
        ),
    ]
